### PR TITLE
Bundle Python and install datasette in a virtual environment on startup

### PR DESCRIPTION
**Pull request by simonw**
Refs #25.

### CODE REVIEW

**Comment by simonw** [comment]
I'm going to see what happens if I have the `test.yml` workflow run `npm run dist` at the end and then attach the generated `.dmg` file as an artifact.

**Comment by simonw** [comment]
That took longer than 5 minutes (total including running the tests) so it timed out.

**Comment by simonw** [comment]
Got this error:

>  ⨯ GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"

**Comment by simonw** [comment]
https://github.com/electron-userland/electron-builder/issues/1693#issuecomment-309246464 says I should pass `--publish=never`

**Comment by simonw** [comment]
OK that seemed to work... there's a 150MB DMG artifact attached to https://github.com/simonw/datasette-app/actions/runs/1188102495

**Comment by simonw** [comment]
It totally worked!

I downloaded the artifact and installed the application from the DMG (to `/Applications/Datasette.app`) - then I ran it and it told me I couldn't because it wasn't signed.

So I went to `Security & Privacy` in the system preferences and clicked "open it anyway"... and it launched and installed everything it needed into `~/.datasette-app/venv` and the application worked!

**Comment by nikvdp** [comment]
Hi @simonw I've been following along with this as we recently faced a similar problem on an electron project and after seeing your recent update on HN thought some of our learnings might be helpful for you.

I've been working on porting our setup into the datasette repo over at [nikdvp/datasette.app](https://github.com/nikvdp/datasette.app) and we seem to have converged on pretty similar solutions! I also started with pyinstaller but quickly switched over to bundling a full venv (using [conda-pack](https://github.com/conda/conda-pack)). Still in flux and not quite ready for a PR yet, but some of https://github.com/nikvdp/datasette might be useful.

Some bits that might be of interest:

- An alternative way to build a single-file binary without relying on pyinstaller. This uses [dgiagio/warp/](https://github.com/dgiagio/warp/), which has some advantages over pyinstaller: in particular it doesn't rely on python's zipfile machinery so many bugs that show up in pyinstaller produced bins don't happen with warp since it runs it the same way python normally does. I've commented it out for now because packing it into a single binary breaks the codesigning process, but may be helpful as an alternative to https://github.com/simonw/datasette/issues/93#issuecomment-754219002. ([code](https://github.com/nikvdp/datasette.app/blob/main/build/build-datasette-bin.sh#L55-L72)).

- Mac Codesigning: once you've gone through the signing certificate export dance you can set the `CSC_LINK` and `CSC_KEY_PASSWORD` env vars in the 'Build Electron app' step as documented [here](https://www.electron.build/code-signing), and electron-builder will then take care of making sure everything is signed correctly.

- the `entitlements.plist` file and associated config in `electron-builder.yml` allow the bundled python interpreter to inherit the codesigning config of the parent electron app. This ended up being super important for us cause it fixed the main issue we ran into in our project, where macos' security prevented the electron app from launching our bundled interpreter.  With these entitlements the Electron app's own signature can be inherited by the bundled python interpreter allowing the electron app to launch it succesfully.

**Pull request merged**
